SUBDIR=	alpm amdpm aps coretemp est
SUBDIR+=intpm kate km lm powernow uguru
SUBDIR+=viapm wbsio perfbias clockmod
SUBDIR+=memtemp amdtemp

# Empty for concurrent build
#
SUBDIR_ORDERED=

.include <bsd.subdir.mk>
